### ISSUE TITLE
请问你是怎么发现这个课程中的人数需要ajax来获取呢？我感觉有点搞不懂这个诶

### ISSUE THREAD

**Issue by YBFJ** [niuyi1017/imooc#1]
```JavaScript
function getNumber(id) {
    return new Promise((resolve, reject) => {


        https.get(numberBaseUrl + id, res => {
            let number = ''
            res.on('data', data => {
                number += data
                number = JSON.parse(number).data[0].numbers
                // console.log(number)
            })
            res.on('end', () => {
                resolve(number)
            })
        }).on('error', err => {
            reject(err)
            console.log(err)
        })
    })
}
```

**Comment by niuyi1017** [comment]
![image](https://user-images.githubusercontent.com/30387148/46578659-b85e4d00-ca37-11e8-9b42-a1762c93ac28.png)
打开控制台就会看到相关的ajax请求。  

原因：慕课网改版后，学习人数改为通过ajax获取。  
发现过程：  
1.node.js中通过cheerio模块获取不到相关的数据，在浏览器控制台用jQuery却能获取到，说明页面加载时学习人数的数据没有一同加载过来，而是通过异步的方式获取的。  
2.在浏览器控制台的network栏中查找学习人数相关的ajax请求信息（请求地址、响应内容）
 
![image](https://user-images.githubusercontent.com/30387148/46578923-f5780e80-ca3a-11e8-9448-e523a9e6b68d.png)

**Comment by YBFJ** [comment]
@niuyi1017 谢谢你，我觉得很奇怪我打开我的控制台看到的和你的不太一样？你是额外点击了什么吗?
![2018-10-09 1 50 28](https://user-images.githubusercontent.com/30866639/46649108-5f72ee00-cbca-11e8-9563-57b22e1bdaad.png)

**Comment by niuyi1017** [comment]
@YBFJ 打开控制台后刷新一下页面

**Comment by YBFJ** [comment]
@niuyi1017 hi，非常抱歉再打扰你，我发现在chorme在我登录慕课网的情况下刷多少次都刷不出来和你一样的xhr，但是我退出登录之后可以刷到。在火狐浏览器中无论我登录还是不登录都是可以刷到和你一样的xhr的，觉得很是神奇。感觉我要卸载谷歌浏览器了，233
![2018-10-09 10 53 33](https://user-images.githubusercontent.com/30866639/46677994-3a0bd180-cc16-11e8-9c2d-27aefe03a722.png)

**Comment by niuyi1017** [comment]
@YBFJ 尝试清除一下chrome的缓存。  
应该是数据缓存到localStorage或者cookie了,所以就不会再次请求了

**Comment by YBFJ** [comment]
@niuyi1017 嗯嗯好的，谢谢你~
